export const themeActions = {
    SWITCH_THEME:"SWITCH_THEME"
}

export const dataActionTypes = {
    GET_DEVELOPER_DATA:"GET_DEVELOPER_DATA", 
    GET_ENGINEER_DATA:"GET_ENGINEER_DATA"
}

export const projectsActionTypes = {
    GET_PROJECTS_DATA:"GET_PROJECTS_DATA",
    GET_ENGINEER_PROJECTS_DATA:"GET_ENGINEER_PROJECTS_DATA", 
    GET_DEVELOPER_PROJECTS_DATA:"GET_DEVELOPER_PROJECTS_DATA"
}

// INACTIVE - SHUT THEM DOWN 

