export const themeActions = {
    SWITCH_THEME:"SWITCH_THEME"
}

export const dataActionTypes = {
    GET_DEVELOPER_DATA:"GET_DEVELOPER_DATA", 
    GET_ENGINEER_DATA:"GET_ENGINEER_DATA"
}

export const skillActionTypes = {
    GET_DEVELOPER_SKILLS:"GET_DEVELOPER_SKILLS", 
    GET_ENGINEERING_SKILLS:"GET_ENGINEERING_SKILLS", 
}

export const infoActionTypes = {
    GET_DEVELOPER_INFO:"GET_DEVELOPER_INFO", 
    GET_ENGINEER_INFO:"GET_ENGINEER_INFO"
}